# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='root_task',
            field=models.IntegerField(null=True),
        ),
    ]
