# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('cost', models.FloatField()),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Risk')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
            ],
        ),
    ]
